/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;


import lexers.Lexer;
import tokens.Tokens;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Charly Ponce
 */
public class AnalizerForm extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public AnalizerForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();
        AceptLbl = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        CancelLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputText.setColumns(20);
        inputText.setRows(5);
        jScrollPane1.setViewportView(inputText);

        AceptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AceptLbl.setForeground(new java.awt.Color(0, 153, 255));
        AceptLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AceptLbl.setText("Aceptar");
        AceptLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AceptLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptLblMouseClicked(evt);
            }
        });

        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TitleLbl.setText("Analizador Léxico");

        CancelLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CancelLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelLbl.setText("Cancelar");
        CancelLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelLbl.setName(""); // NOI18N
        CancelLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addComponent(TitleLbl)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AceptLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitleLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptLblMouseClicked
        // TODO add your handling code here:

        for (String line : inputText.getText().split("\\n")) {        
            File file = new File("file.txt");
            PrintWriter write;
            try {
                write = new PrintWriter(file);
                write.print(inputText.getText());
                write.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AnalizerForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                Reader reader = new BufferedReader(new FileReader("file.txt"));
                Lexer lexer = new Lexer(reader);
                String result = "";
                while (true) {
                    Tokens tokens = lexer.yylex();
                    if (tokens == null) {
                        result += "END";
                        inputText.setText(result);
                        return;
                    }
                    switch (tokens) {
                        case Suma: case Division: case Multiplicacion: case Resta: case Potencia:
                            result += tokens + "\n";
                            break;
                        case Digito:
                            result += "Digito \n";
                            break;
                        case NewLine:
                            result += "Expresion ended " + lexer.line + " \n";
                            break;
                        case Operacion:
                            result += "Operación matemática \n";
                            break;
                        case ERROR:
                            result += "Error \n";
                            break;
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AnalizerForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AnalizerForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_AceptLblMouseClicked

    private void CancelLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AceptLbl;
    private javax.swing.JLabel CancelLbl;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JTextArea inputText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
